spring:
  datasource:
    username: backend2team
    password: supercoding09
    url: jdbc:mariadb://db-baeckend2team.cryqvukdhzno.ap-northeast-2.rds.amazonaws.com:3306/shop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


security:
  jwt:
    header: Authorization
    secret: superCoding
    token-validity-in-seconds: 604800

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework : DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
