spring:
  datasource:
    username: backend2team
    password: supercoding09
    url: jdbc:mariadb://db-baeckend2team.cryqvukdhzno.ap-northeast-2.rds.amazonaws.com:3306/shop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    header: Authorization
    secret: superCoding
    token-validity-in-seconds: 604800

aws:
  accessKeyId: AKIA2WSJ73WOI2ZIWIMW
  secretKey: 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
  region: ap-northeast-2
  s3:

    bucketName: project2team

logging:
  level:
    org.springframework.security: DEBUG




#<사용자 이름 : S3Aceess>
#1. accessKey :
#2. secretKey :

